[package]
name = "slot"
version.workspace = true
license-file.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
slot-cli.workspace = true

clap.workspace = true
tokio.workspace = true
env_logger = "0.11.3"
num-bigint.workspace = true
update-informer.workspace = true
