name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.87.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      # Required to build Katana at the moment.
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy
      # Required to build Katana at the moment.
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cargo clippy --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1

  ensure-windows:
    env:
      CMAKE_POLICY_VERSION_MINIMUM: "3.5"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-pc-windows-msvc
      # Required to build Katana at the moment.
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cargo check --target x86_64-pc-windows-msvc --workspace
