name: e2e

on:
  pull_request:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.87.0

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-dev:v1.7.1
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy
      # Required to build Katana at the moment.
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Required to build Katana.
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.2"
      - run: sh ./scripts/e2e.sh
        env:
          SLOT_AUTH: ${{ secrets.SLOT_AUTH }}
