name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy

    - name: Check Rust formatting
      run: cargo +nightly fmt --all -- --check

    - name: Run Rust linting (Clippy) - strict mode
      run: cargo clippy --all-targets --all-features -- -D warnings -D future-incompatible -D nonstandard-style -D rust-2018-idioms -D unused

    - name: Build project
      run: cargo build --all-targets

    - name: Run tests
      run: cargo test --all-features